Update the script to latest changes in openQA
- Add job group for SLES 15 SP7 and 16.0
- Improve build_check by searching the exit status inside logs with egrep

diff --git a/openqa-search-maintenance-core-jobs b/openqa-search-maintenance-core-jobs
--- a/openqa-search-maintenance-core-jobs
+++ b/openqa-search-maintenance-core-jobs
@@ -28,10 +28,12 @@ declare -A dict_group=(
     ["15-SP4"]=439
     ["15-SP5"]=490
     ["15-SP6"]=546
+    ["15-SP7"]=644
     ["12-SP3"]=106
     ["12-SP5"]=282
     ["15-SP4-TERADATA"]=521
     ["12-SP3-TERADATA"]=191
+    ["16.0"]=656
 )
 
 readonly url_dashboard_qam="${url_dashboard_qam:-"http://dashboard.qam.suse.de"}"
@@ -176,8 +178,8 @@ search_build_checks() {
     if [[ -n $logs ]]; then
         echo "Build checks url: $index"
         for log in $logs; do
-            echo "curl -sLk '$index/$log' | grep ' + exit '"
-            curl -sLk "$index/$log" | grep '+ exit ' || true
+            echo "curl -sLk '$index/$log' | grep -E --text ' \+ exit | failed| passed| skipped|Result: | test result: '"
+            curl -sLk "$index/$log" | grep -E --text ' \+ exit | failed| passed| skipped|Result: | test result: ' || true
             echo ""
         done
     fi
